### ISSUE TITLE
Option to login to Google Account no longer appears

### ISSUE THREAD

**Issue by gbcox** [mattflaschen/goo.gl-lite#11]
Trying to use with my Google Account, but the option to login no longer appears.

**Comment by mattflaschen** [comment]
The version (1.9) with Google Account support was preliminarily-reviewed before.  This state is [no longer available](https://blog.mozilla.org/addons/2016/08/19/a-simpler-add-on-review-process/), so I have to resolve #10 before it's installable via addons.mozilla.org .

You can follow that task.
